### ISSUE TITLE
Document question

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#10]
"diffing" --> "defying"? 

> We saw that the complex diffing can be avoided.
> https://github.com/riot/riot.github.io/blob/master/compare.md#string-based-vs-dom-based

**Comment by tipiirai** [comment]
Not sure if "diffing" is an official word, but it seems to be in real use. Take for example this project

https://github.com/Matt-Esch/virtual-dom

> "A Virtual DOM and diffing algorithm"

**Comment by cognitom** [comment]
gotcha! `diff` + ing
@tipiirai thanks!
