### ISSUE TITLE
"each" example for custom tags is a bit confussing

### ISSUE THREAD

**Issue by ifraixedes** [riot/riot.github.io#103]
I've found a bit confussing the documentation of [`each` for custom tags](http://riotjs.com/guide/#looping-custom-tags).

```
<todo-item each="{ items }" data="{ this }"></todo-item>
```

Set the values on each element of items to the context of the tag (`this`) as it's mentioned; if any other html attributes is provided then they are set as a property in `opts` as Riot tags operate.

The example shown in the documentation is a bit confusing due the `{ this }` inside the data; I understand that if you are very experienced in RiotJS is quite straightforward to understand but I don't that it's clear for new commers

I'm wondering if that I'm saying here make sense and it does I will send a PR with a bit more explanation in the section.

**Comment by wintercounter** [comment]
In jQuery and many other library `this` refers to the currently looped element.

```js
$('.elem').each(function(){
    console.log(this) // Current DOM Element
})
```

The logic is the same here (each creates a new context, just like a callback function), I don't think it's confusing that much.

**Comment by ifraixedes** [comment]
I cannot remember this now, I wrote quite a few weeks ago.
Maybe I'm not that much used to use frameworks, ending up using a lot the browser API.

Anyway, thanks.
