### ISSUE TITLE
Scoped CSS: what happens once ?

### ISSUE THREAD

**Issue by sylvainpolletvillard** [riot/riot.github.io#114]
http://riotjs.com/guide/#scoped-css

"This happens once, no matter how many times the tag is initialized."

What happens once ? I got confused when trying to translate this. I'm suppose it is related to the way Riot adds scoped CSS, but I think we would need more explainations here.

**Comment by cognitom** [comment]
The paragraphs in wrong order, I think.

> You can put a style tag inside. Riot.js automatically takes it out and injects it into <head>.
> This happens once, no matter how many times the tag is initialized.

It should be like above, and it would make sense.

**Comment by cognitom** [comment]
Thanks!
