### ISSUE TITLE
Claim http://stackshare.io/riot

### ISSUE THREAD

**Issue by avimar** [riot/riot.github.io#13]
http://stackshare.io/riot doesn't have the logo.

I don't know what else you can do by claiming it.

**Comment by cognitom** [comment]
They say:

> Please enter your company email address 
> http://stackshare.io/claim-service/riot

@tipiirai ?

**Comment by tipiirai** [comment]
Is this really important? Got lost on their UI and made me frustrated :)

**Comment by tipiirai** [comment]
Does this look right? http://stackshare.io/riot

**Comment by avimar** [comment]
Better! Cool.
