### ISSUE TITLE
Some dead links in `zh/guide`

### ISSUE THREAD

**Issue by chinesedfan** [riot/riot.github.io#132]
Nearly every anchor point is failed. For examples:

```
自定义标签示例 -> 预处理 -> 预处理器
循环 -> 上下文 -> 标签实例
加载 -> 如何使用 jQuery -> 标签生命周期
```

Maybe it is a bug of MarkDown or Jekyll.

**Comment by Centaur** [comment]
Thank you for reporting this.  Allow me some time to check it out.

**Comment by k-kuwahara** [comment]
@chinesedfan 
As it is now, I fixed the document on version 2 of `zh`, so please check it. If it does not matter, please close it.
