### ISSUE TITLE
Server Side render

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#139]
Regarding http://riotjs.com/guide/#server-side-rendering
The following sentence implies that there are problems and that features, other than loops and conditionals are maybe not supported?

Loops and conditionals _are_ supported.

It would be nice to see why it was decided to highlight that these two features that they _do_ work.

**Comment by GianlucaGuarini** [comment]
probably this is something we should ask @tipiirai . We could remove it anyway. Btw the doc should be updated for the upcoming riot@3.0.0 release
