### ISSUE TITLE
Restore translated pages

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#155]
A lot of external pages refer to the url like `http://riotjs.com/ja/api/observable/`, but these pages has been moved to under `http://riotjs.com/v2`. So we may get 404.
GitHub Pages doesn't support redirection, so I think we need to simply restore the translated docs back, and mark them `v2` obviously in some way.

@GianlucaGuarini thoughts?

**Comment by GianlucaGuarini** [comment]
@cognitom I think we could use this https://help.github.com/articles/redirects-on-github-pages/ to redirect to `/v2/{ pageName }`

**Comment by cognitom** [comment]
@GianlucaGuarini thanks for remembering me about `jekyll-redirect-from`! I've added it and set up the redirection in Japanese pages. And I'm starting the translation process #158.

BTW, I feel we need to simplify our [CONTRIBUTING.md](https://github.com/riot/riot.github.io/blob/master/CONTRIBUTING.md#translation) for more easy translation. I'll open a new PR about it later.

FYI, @riot/collaborators you could add the redirect settings in your frontmatter like this:

```yml
redirect_from: "/ja/guide/application-design"
```

or

```yml
redirect_from:
  - "/ja/guide"
  - "/ja/guide/"
```
