### ISSUE TITLE
`play` links not working

### ISSUE THREAD

**Issue by karlpatrickespiritu** [riot/riot.github.io#157]
![image](https://cloud.githubusercontent.com/assets/10472504/20641523/e6209894-b434-11e6-8674-a223463a8fed.png)

**Comment by cognitom** [comment]
@karlpatrickespiritu I couldn't find any error on the page...
Could you explain more?

**Comment by karlpatrickespiritu** [comment]
@cognitom try going to http://riotjs.com/play/. Can't actually see the live demos. I checked the console and that error showed up.

**Comment by GianlucaGuarini** [comment]
I also don't see any error, try to clear you cache @karlpatrickespiritu

**Comment by karlpatrickespiritu** [comment]
Cleared my cache. Still seeing the error. Also on firefox.

**Comment by karlpatrickespiritu** [comment]
![image](https://cloud.githubusercontent.com/assets/10472504/20641661/d514d9f4-b437-11e6-81e8-aaa7cb1905be.png)

**Comment by karlpatrickespiritu** [comment]
hmmnn.

![image](https://cloud.githubusercontent.com/assets/10472504/20641697/c804177e-b438-11e6-8378-90b6275b98a8.png)

**Comment by karlpatrickespiritu** [comment]
or is it just my machine probably having malwares.
