### ISSUE TITLE
The migration guide leaves a few points open

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#159]
* Since `name` and `id` for selecting elements is deprecated - does the user have to use `ref="example"` for his subtags too, to access them in `this.tags.example`?
* Now that spaced events are not supported anymore - is listen to `*` gone too? A short notice would be nice.
* No update before mount: this leaves open for interpretation if riot fires it AFTER mount or not at all.
* "Scoped css **by default**" - means you can disable it back on?

**Comment by cognitom** [comment]
@MartinMuzatko your pr is always welcome 😄 

Here's quick answers:

1. As mentioned in the example in the guide, access them via `this.refs.example`
2. Nothing has been changed on `*`
3. *"only fired on the consequent update calls"* seems clear for me. Isn't it?
4. No unscoped option, AFIK

**Comment by GianlucaGuarini** [comment]
closed with #164
