### ISSUE TITLE
Tagging and branching convention

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#16]
Can I add the `v2.2.4` tag to the HEAD?
Then I'd like to:
- ~~make `ja/v2.2.4` branch~~ _done._
- ~~merge #14, #15, #17~~ _done._

I'm thinking about such a convention:
- no dev branch for `riot/riot.github.io`
- tag a new `v2.x.x` just after each Riot release
- make `lang/v2.x.x` branches for translation
- tag `v2.x.x-lang` after translated

How about?
![artboard 1](https://cloud.githubusercontent.com/assets/16032/9560446/6383fc9c-4e4f-11e5-9b2f-0a4e81121f15.png)

cc: @tipiirai @GianlucaGuarini @aMarCruz @rsbondi @narikei

**Comment by aMarCruz** [comment]
Looks good.
Whenever I get the first new version of the compiler, I would like to start a Spanish translation.

**Comment by cognitom** [comment]
:+1: Spanish translation!

We got to invite @Centaur, too. He has Chinese one.
https://github.com/Centaur/riotjs_doc_cn

**Comment by Centaur** [comment]
Ok. I will send pull-requests for Chinese version.

**Comment by cognitom** [comment]
@Centaur oh, really? Great! I'm so happy to hear that :laughing:

I'll make a simple check list for translation, soon.

**Comment by GianlucaGuarini** [comment]
@cognitom I still don't know whether the `import.sh` script should handle also the translation files for our submodules. What happens if we update the `riot-observable` in it's own repo (importing the new README.md file via script )? Will the `ja/observable.md` file be out of sync?

**Comment by cognitom** [comment]
@GianlucaGuarini I'm thinking about removing i18n files from submodules. Then translator will be able to focus on `riot/riot.github.io`. It seems easy and simple.

**Comment by GianlucaGuarini** [comment]
Ok I agree

**Comment by cognitom** [comment]
Thanks. I'll do it ;)

**Comment by cognitom** [comment]
Done.

- tag `v2.2.4` added
- branch `ja/v2.2.4` created
- issue #19 opened: this is a task list for catching up to v2.2.4

And also, I've [removed i18n files](https://github.com/riot/route/commit/e0c036068f763ab8bd66141863ab4d3b3dca70ae) from `riot/route`.

**Comment by cognitom** [comment]
Here's [some branches](https://github.com/riot/riot.github.io/branches) for translation. Feel free to send your PRs to each :-)

- `ch/v2.2.4`: @Centaur 
- `de/v2.2.4`: @MartinMuzatko 
- `es/v2.2.4`: @aMarCruz 
- `fr/v2.2.4`: @sylvainpolletvillard
- `ja/v2.2.4`: @cognitom
- `nl/v2.2.4`: @rvanzon

**Comment by sylvainpolletvillard** [comment]
Can you make a tag for 2.3.1 ?

**Comment by kfreiman** [comment]
Just for clarity: when new english version is tagged, we should translate the diff between the new tag and corresponding tag of latest translation.

```sh
git diff v2.2.4 v2.3.1 -- index.md
```

```diff
 ### 3. Tiny size
 
-<small><em>polymer.min.js</em> – 138KB</small>
+<small><em>react.min.js</em> – {{ site.react.size }}KB</small>
 <span class="bar red"></span>
 
-<small><em>react.min.js</em> – 119KB</small>
-<span class="bar red" style="width: {{ 138 / 119 * 100 }}"></span>
+<small><em>polymer.min.js</em> – {{ site.polymer.size }}KB</small>
+<span class="bar red" style="width: {{ site.polymer.size | divided_by: site.react.size | times: 100 }}%"></span>
 
 <small><em>riot.min.js</em> – {{ site.size_min }}KB</small>
-<span class="bar blue" style="width: {{ site.size_min / 121 * 100 }}%"></span>
+<span class="bar blue" style="width: {{ site.size_min | divided_by: site.react.size | times: 100 }}%"></span>
 
 - Fewer bugs
 - Faster to parse and cheaper to download
```

**Comment by cognitom** [comment]
@sylvainpolletvillard I've tagged v2.3.1. Thanks for reminding.
@kfreiman exactly :+1:
