### ISSUE TITLE
Integrating the Riot Cheatsheet

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#162]
With the release of 3.0.0, I was offered to implement my privately maintained [riot cheatsheet](http://martinmuzatko.github.io/riot-cheatsheet/) directly into the github page. See https://github.com/riot/riot.github.io/pull/152#issuecomment-262331931.

I'd love to know further implementation details and conditions.
Is it just a link to the gh page? Do we want it to have it maintained via this repo?

Thanks in advance.

**Comment by GianlucaGuarini** [comment]
@MartinMuzatko The integration of riot cheatsheet should be done following these steps:

- add a new file in this repo called `guide/cheatsheet.md`
- merge all [these contents](https://github.com/MartinMuzatko/riot-cheatsheet/tree/gh-pages/docs/3.0.0) in that file 
- add a new link [here](https://github.com/riot/riot.github.io/blob/master/_includes/guide-tabs.html)  to that page
- Normalize the structure of the `cheatsheet.md` file to make it similar to the other guide `md` files and adding: 
```
---
layout: default
title: Cheatsheet
---

{% include guide-tabs.html %}
```

Of course @MartinMuzatko you can maintain this file and we could add other hints as well. At this point I think you can add a link to that page from your repo saying that the cheatsheet was moved on the official riot website.

Let me know what you think or if you want to keep having these files in a separate repo

**Comment by GianlucaGuarini** [comment]
Nothing happened here since 1 year so I am going to close it
