### ISSUE TITLE
Proposal: separated repo for translations

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#171]
Hi all. I'm thinking about purging all our translations from this repo and moving them into new repos for each.

### Why?

We're translating [the doc v3 into Japanese](https://github.com/riot/riot.github.io/pull/158), and getting done almost. But it was hard to read [the diff of v3.0.0 from v2.3.18](https://github.com/riot/riot.github.io/compare/v2.3.18...riot:v3.0.0) (<--pls click this link). We needed only the English part, but all our translation was included. That makes it so hard to pick the part which needs updating.

### Solution (proposal)

Adds five new repos for translated documents:

- `riot/riot.github.io`: English only, simple.
- `riot/es`: Spanish translation (new repo)
- `riot/fr`: French translation (new repo)
- `riot/ja`: Japanese translation (new repo)
- `riot/ru`: Russian translation (new repo)
- `riot/zh`: Chinese translation (new repo)

The good point is that we don't have to change the url even though the repo has been changed.

- before: http://riotjs.com/ja --> https://github.com/riot/riot.github.io/tree/master/ja
- after: http://riotjs.com/ja --> https://github.com/riot/ja/tree/gh-pages

@riot/collaborators @riot/core-maintainers any feedback is welcome!

**Comment by MartinMuzatko** [comment]
@cognitom are there resources we can inherit/depend on?
Updating the same sass on each repo would be a pain in the ass :)
What do you suggest? git submodule? sass as npm module?

**Comment by cognitom** [comment]
@MartinMuzatko how about simply pointing absolute path?
http://riotjs.com/style.css
http://riotjs.com/script.js

**Comment by GianlucaGuarini** [comment]
I think i will use only this repo for the doc since there is no big activity by the maintainers of the other languages. The next doc will be probably only in English
