### ISSUE TITLE
Document Translation Guide (draft)

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#18]
Basically, take it easy. Just pls follow the convention of originals :-)
Here's some points I found while [translating them into Japanese](http://riotjs.com/ja). I hope it would help someone.

## How to start:

- [Pick your language code](http://www.sitepoint.com/web-foundations/iso-2-letter-language-codes/). For example: `ja`, `zh`, `es`, `de`, ...etc.
- Make a new directory at `/` (root) with the name from your language code. For example: [/ja/](https://github.com/riot/riot.github.io/blob/master/ja/)
- Put your translated files into your directory. Follow the original structure. For example:
  - [/index.md](https://github.com/riot/riot.github.io/blob/master/index.md) --> [/ja/index.md](https://github.com/riot/riot.github.io/blob/master/ja/index.md)
  - [/api/index.md](https://github.com/riot/riot.github.io/blob/master/api/index.md) --> [/ja/api/index.md](https://github.com/riot/riot.github.io/blob/master/ja/api/index.md)
- Make some HTML parts in `/_includes/`. Create a new directory there and put these files into it. For example:
  - [/_includes/ja/api-tabs.html](https://github.com/riot/riot.github.io/blob/master/_includes/ja/api-tabs.html)
  - [/_includes/ja/guide-tabs.html](https://github.com/riot/riot.github.io/blob/master/_includes/ja/guide-tabs.html)
- Make a Jekyll template for your language in `/_layouts/`. For example:
  - [/_layouts/ja.html](https://github.com/riot/riot.github.io/blob/master/_layouts/ja.html)

## How to check the site locally:

See [Jekyll document](http://jekyllrb.com/docs/quickstart/). Don't worry, easy steps. Basically just two:
- `$ sudo gem install jekyll`
- `$ jekyll serve` at the root directory of this project.

## How to manage it continuously:

- We're discussing about [Tagging and branching convention](https://github.com/riot/riot.github.io/issues/16).
- Don't work hard alone, invite your friend as a translator or a reviewer.
- Make a team for your language!

cc: @aMarCruz @Centaur @MartinMuzatko @narikei @tipiirai

**Comment by MartinMuzatko** [comment]
Thanks for this little guide, please create a CONTRIBUTING.md file with the contents of this issue :)

**Comment by cognitom** [comment]
@MartinMuzatko ok, I'll do it.
It could be nice to open a new issue about German translation ;-)

**Comment by MartinMuzatko** [comment]
done, see #21 :)

**Comment by sylvainpolletvillard** [comment]
Installing Jekyll on Windows can be painful, but it looks like I get it working. Follow these instructions : http://jekyllrb.com/docs/windows/ ; and good luck !

**Comment by MartinMuzatko** [comment]
Thanks a lot @sylvainpolletvillard, I'll have a look!

**Comment by aMarCruz** [comment]
Thanks @sylvainpolletvillard , this link is a must.

**Comment by cognitom** [comment]
I've just added CONTRIBUTING.md
https://github.com/riot/riot.github.io/blob/master/CONTRIBUTING.md

My English is awful as you know..., feel free to fix it. Thanks!
