### ISSUE TITLE
Live demo doesn't work properly in Safari Safari 10.1 on Mac OS X 10

### ISSUE THREAD

**Issue by kesla** [riot/riot.github.io#187]
When changing data in the editor the old html is still around (but in the background)

Hard to explain, here's an example of what happens when I changed a letter:
![screen shot 2017-05-25 at 18 32 19](https://cloud.githubusercontent.com/assets/74128/26473299/9f2daeb4-4178-11e7-90d5-6dcee745f45d.png)

**Comment by GianlucaGuarini** [comment]
this appears to be a font issue (on your machine) not a riot one thanks anyway for reporting it.

**Comment by kesla** [comment]
@GianlucaGuarini Weird, something on my machine must've been temporarily off. Can't reproduce today.

Thanks for taking a look at it!
