### ISSUE TITLE
Document usage of <script> for in-browser compilation

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#188]
Hello! I found that on http://riotjs.com/guide/compiler, there is no word about using <script> tags within a tag component if inlined, instead of loading another file.

Because I get `Unexpected token <` when using <script> within <script type="riot/tag">

See http://plnkr.co/edit/fnuOb1tWGhioN0428yZ9?p=preview

I believe this was on purpose. Not sure though. @GianlucaGuarini

**Comment by GianlucaGuarini** [comment]
@MartinMuzatko yes i guess it would be worth to drop a couple of lines about it [here](http://riotjs.com/api/compiler/#-riotcompiletag). Would you mind making a pull request?

**Comment by MartinMuzatko** [comment]
Sure @GianlucaGuarini ! Just wanted to have your approval :)
