### ISSUE TITLE
ja/v2.2.4

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#19]
It's time to catch up Japanese docs to [v2.2.4]([v2.2.4](https://github.com/riot/riot.github.io/tree/v2.2.4))!
I've made a new branch [ja/v2.2.4](https://github.com/riot/riot.github.io/tree/ja/v2.2.4). So feel free to send your PR to it.

- [ ] Drop IE8 https://github.com/riot/riot.github.io/commit/1dfa717c576f686c22fc31e4c75096e3d8805ed0
- [ ] Minor changes https://github.com/riot/riot.github.io/commit/4bb13d2a6ac5465b38b44d7efa6e53071aa97c80
- [ ] Home page fixes https://github.com/riot/riot.github.io/commit/7d7b85b3d0765e076961156a854990b2699ca3d9
- [ ] Fix grammar/style and add scoped css to list https://github.com/riot/riot.github.io/commit/9a9af8b20196b5eacf26e3ff9100b840545ed113
- [ ] info regarding the usage of underscore-prefixed variables https://github.com/riot/riot.github.io/commit/8a395d839fe28b3fcbb0c6a067f41ddf964f80ae
- [ ] Correct guide/index.md typo https://github.com/riot/riot.github.io/commit/4c1107f85db99c1f61685b8a779e0d15c9d5dfcd

**Comment by cognitom** [comment]
I'd like to automate gathering the commits like above...

**Comment by emadurandal** [comment]
Hi, I'd like to participate in the Japanese translation project.
I have some of OSS translation experiences. (Ember.js, Fabric Engine, etc...)

Although I have not yet used to the workflow in github, I will do my best :)

**Comment by cognitom** [comment]
@emadurandal thank you. Happy to hear that :-)

We're translating the document on `ja/2.2.4` now. Feel free to send PR to this branch!

![image](https://cloud.githubusercontent.com/assets/16032/9560446/6383fc9c-4e4f-11e5-9b2f-0a4e81121f15.png)

**Comment by k-kuwahara** [comment]
@cognitom 
I have found a mistype at this page "http://riotjs.com/ja/guide/compiler/".  
Although it is the second item of "使い方"

```
# 指定フォルダにファイルをにコンパイル
↓
# 指定フォルダにファイルをコンパイル
```

perhaps, I think the above is correct. How is it?

**Comment by cognitom** [comment]
@k-kuwahara right!
Feel free to send PR ;)

**Comment by cognitom** [comment]
A happy new year!
It's time to move v2.3.x. Thanks to @eliot-akira, the translation of 2.3.12 has almost completed. So I'd like to skip this version.
I'm opening a new issue about `ja/v2.3.12` #93
