### ISSUE TITLE
Enable ssl certificate for riotjs.com

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/riot.github.io#207]
The riotjs.com is managed and payed by @tipiirai and I don't have any access to it. I would like to enable a SSL certificate for it but I can't. 
@tipiirai could you please transfer it or giving me the credentials? I will happy to maintain it and pay all the costs for it.

**Comment by GianlucaGuarini** [comment]
@tipiirai could you give us an update on this issue? I am stuck with this problem

**Comment by GianlucaGuarini** [comment]
If there will be no updates on this issue I will be forced to migrate to https://github.com/js-org/dns.js.org

**Comment by GianlucaGuarini** [comment]
I started the migration to riot.js.org the domain riotjs.com is temporary down

**Comment by jtsmedley** [comment]
Is this not important?

(in the gh-pages branch for project pages)??

**Comment by GianlucaGuarini** [comment]
@jtsmedley on our side it's [everything configured properly](https://github.com/riot/riot.github.io/blob/master/CNAME)

**Comment by indus** [comment]
Because some people noticed and might wonder: In such a case where a vivid page already exists it is an option to just add a file name "CNAME_" (or something similar) until I have processed the request. That expresses your will to use the subdomain good enough but the redirect would not kick in. The file could then easily be renamed afterwards and everything should work instantaneous without a long downtime.
(I'm not promoting this method that much because it would mean more work for me. I then have to check every request not once but twice - but for a well-known page with a active userbase it is a reasonable thing to do)
✌️

**Comment by GianlucaGuarini** [comment]
@indus thank you for your help and don't worry about the down time. I am proud to use finally a js.org domain. This issue was solved now I will need to fix all the links in all our packages

**Comment by GianlucaGuarini** [comment]
side note: I have written to the github help in order to know whether they could redirect with a 301 to the new domain. I am waiting their response

**Comment by cekvenich** [comment]
If it helps, You don't need certs or certs anymore.
Just run any modern http server, ex:  http://caddyserver.com 
and it will transparently generate tls . You. do. nothing.
Also, any CDN will do it also, transparently generate tls.

All you need is control of DNS name.

**Comment by GianlucaGuarini** [comment]
thank you @cekvenich but the problem here was not only the certificate. The riotjs.com domain is maintained and managed by someone that doesn't belong to the riot project since 2 years

**Comment by SusanthCom** [comment]
Good work. @GianlucaGuarini  @indus
...
`riotjs.org` and `riotjs.info` is free to register.

**Comment by SusanthCom** [comment]
Good work. @GianlucaGuarini  @indus
...
`riotjs.org` and `riotjs.info` is free to register.

If you like any one of them, am happy to sponsor the domain.

> **`riotjs.org`** looks like a good choice. ( similar to :  vuejs.org, infernojs.org, reactjs.org ... )

you will have full ownership and admin rights too.
