### ISSUE TITLE
Riotjs.com 404 Not Found

### ISSUE THREAD

**Issue by ienugr** [riot/riot.github.io#210]
Hi, I've got an error 404 when accessing [riotjs.com](http://riotjs.com) and it says:
```
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

GitHub Status — @githubstatus
```

Here is a screenshot:
![image](https://user-images.githubusercontent.com/10795629/39959781-4829dfbe-5641-11e8-9b26-074096add7fb.png)

Thank you

**Comment by GianlucaGuarini** [comment]
please check this https://github.com/riot/riot.github.io/issues/207
