### ISSUE TITLE
Setup redirect from riotjs.com to riot.js.org

### ISSUE THREAD

**Issue by chrisdothtml** [riot/riot.github.io#213]
For SEO, as well as any links sitting out there on the web. One of my coworkers just assumed the site was just down because they visited .com and it wasn't available

**Comment by GianlucaGuarini** [comment]
I already wrote to github support and they answered they can't help us.
The only possibility is to get in touch with @tipiirai , the domain owner. I can't get news from him since more than one year.

**Comment by chrisdothtml** [comment]
Oh man, that sucks. Maybe reach out to https://iwantmyname.com (the site that domain was registered with) and see if they can help

**Comment by GianlucaGuarini** [comment]
I wrote again to @tipiirai hoping to get an answer anytime soon 🙏

**Comment by GianlucaGuarini** [comment]
@tipiirai gave me the access to the domain and I was able to handle the redirects. It should be everything fine now
