### ISSUE TITLE
Address removal of optional script tags

### ISSUE THREAD

**Issue by youbastard** [riot/riot.github.io#219]
Currently, the use of "script" in a riot tag is optional, but it will become obligitory with the release of 4.0.

Would it be better to update the documentation now to use this convention consistantly? It will help users have one less thing to worry about when upgrading to the next version. 

Additionally, using <script> tags in examples will gives better syntax highlighting.

**Comment by GianlucaGuarini** [comment]
@youbastard I would like to keep this update for when we will release riot@4 for now let's avoid unecessary changes to the doc

**Comment by GianlucaGuarini** [comment]
closing this issue since Riot.js@4 was released and the documentation was update accordingly
