### ISSUE TITLE
fr/v2.2.4

### ISSUE THREAD

**Issue by sylvainpolletvillard** [riot/riot.github.io#23]
I started to work on French translation: https://github.com/sylvainpolletvillard/riot.github.io/commits/fr/v2.2.4

Feel free to join ;)

**Comment by tipiirai** [comment]
Awesome! Thank you!

**Comment by sylvainpolletvillard** [comment]
Okay I think I'm almost done. Finishing Riot 1.0 doc and checking all the links, merging with master, then I will PR the whole thing.

**Comment by tipiirai** [comment]
:+1:

**Comment by cognitom** [comment]
@sylvainpolletvillard great job!
Now, French docs are here!
http://riotjs.com/fr/

We'll add a language pulldown on the header, ASAP ;-)
