### ISSUE TITLE
browser compilation - 4.0 docs change stance on production readiness, why?

### ISSUE THREAD

**Issue by jfols** [riot/riot.github.io#234]
From the v3 docs: 

> Compilation phase is basically free and takes no time at all. Compiling a timer tag 30 times takes 2 milliseconds on a regular laptop. If you have a crazy page with 1000 different timer-sized tags, the compilation takes around 35ms.
> 
> The compiler weights only 3.2KB (1.7K gzipped) so you can safely perform client side compilation on production without download or performance or issues.

From the v4 docs:

> Riot tags can be compiled also in directly in your browser for quick prototypes or tests.

> The Compilation phase is asynchronous and it will not block your application rendering. However you should use the browser compilation only for prototyping or for quick experiments.
> 
> Pre-compilation on gives you following benefits:
> 
> Ability to compile tags with your favorite pre-processor.
> Big performance benefit. No need to load and execute the compiler on browser.
> Sourcemaps support for debugging.

- - -

While there are obvious benefits to pre-compilation, there are also advantages of in-browser compilation:

- no pre-processor necessary
- simpler dev environment and deployment; potentially just vanilla static web assets
- super simple component reuse on any type of website (wordpress, etc.)
- Time To First Hello World (this is super important to attract newer, less experienced web developers and even more experienced devs just playing around with riot)
- differentiation from react/vue
- more?

I think the option of in-browser compilation, even in production, is a massive advantage for riot adoption and is straight up **cool**. Perhaps the documentation could take a more neutral stance and allow developers to choose which compilation strategy is best for any particular project rather than discouraging in-browser compilation in production?

Is there any reason why using in-browser riot compilation is strictly _bad_ idea other than a performance hit and lack of source maps?

**Comment by GianlucaGuarini** [comment]
> Is there any reason why using in-browser riot compilation is strictly bad idea other than a performance hit and lack of source maps?

If you are a Riot.js user you are probably using it for its simplicity and its tiny source code. Loading 400kb javascript (`riot+compiler.min.js`) in your production application is not a smart idea nor a thing I would recommend or do myself in any case. That's it, encouraging it in the official documentation doesn't seem to me the right way to describe how Riot.js user should use it.

**Comment by jeremycook** [comment]
Thanks @GianlucaGuarini. It helped me understand where you are coming from and that there are no technical limitations that prevent riot+compiler.min.js from being used in production. Would it be reasonable to paraphrase what you said here in the docs? Changing the text to read like this for example:

> The Compilation phase is asynchronous and it will not block your application rendering. However you should use the browser compilation only for prototyping or for quick experiments. riot+compiler.min.js is about 20 times larger than riot.min.js. Parsing and executing the additional JavaScript, and compiling templates in-browser negatively affects performance.

It still has the strong assertion that riot+compiler.min.js should not be used in production, but provides a rationale, allowing devs to reason about trade-offs for their own uses. For example: using riot+compiler.min.js in an intranet site seems reasonable where ease of development tends to be more important than performance, and there are no mobile devices and bandwidth is not an issue.
