### ISSUE TITLE
Riot.js@4 Japanese translation

### ISSUE THREAD

**Issue by k-kuwahara** [riot/riot.github.io#235]
We need your help! Feel free to send your PR!
日本語の翻訳者を求めています! 次の手順で参加をお待ちしています 😉

 * このページで、どのページを翻訳するか宣言する (コメントする)
* `master` ブランチをフォークする
* `v4/ja/{翻訳するページ}` でブランチを切る
* 翻訳をv4に合わせて修正する
* コミット & プッシュした後、本家のmasterブランチに対して PR を出す

Todos:

* [x] : ~`/` - @k-kuwahara~ (fin)
* [x] :  ~`/documentation/` - @k-kuwahara~ (fin)
* [x] : ~`/api/`~ (fin)
  * [x] : ~`Core API` - @k-kuwahara~ (fin)
  * [x] : ~`Component Object` - @k-kuwahara~ (fin)
* [x] : ~`/compiler/`~ (fin)
  * [x] : ~`Introduction` - @ShiMeiWo~ (fin)
  * [x] : ~`In-browser compilation` - @ShiMeiWo~ (fin)
  * [x] : ~`Pre-compilation` - @ShiMeiWo~ (fin)
  * [x] : ~`Pre-processors` - @ShiMeiWo~ (fin)
  * [x] : ~`Post-processors` - @ShiMeiWo~ (fin)
* [x] : ~`/faq/` - @k-kuwahara~ (fin)
* [x] : ~`/migration-guide/` - @k-kuwahara~ (fin)

**Comment by ShiMeiWo** [comment]
`/compiler/`の翻訳をしようと思ったのですが、分量が多いため、日々の仕事の合間に一人で行うと期間がかかると思います。それでもよろしいでしょうか？

**Comment by yumemi-kuwahara** [comment]
@ShiMeiWo 
それでも良いですし、途中途中でPR出していただいても良いですし、分担する形でも大丈夫ですー。

**Comment by ShiMeiWo** [comment]
@yumemi-kuwahara 
了解いたしました。では、masterをフォークして、「v4/ja/compiler」ブランチを派生させて
そこで編集することにいたします。
ある程度の区切りを付けたら、PRを出すようにしたいと思います
（その後続けられるかは、その時に改めて考えたいと思います。）

ちなみに、編集中のファイルはこちらの方になっております。
https://github.com/ShiMeiWo/riot.github.io/blob/v4/ja/compiler/ja/compiler.md

**Comment by GianlucaGuarini** [comment]
I don't understand Japanese but I am sure that we need at some point a language switcher or a link in the footer at some point. PRs are welcome ✌️

**Comment by k-kuwahara** [comment]
I close this issue. Because all the documents have been translated into Japanese.

**Comment by GianlucaGuarini** [comment]
we need a link somewhere to the Japanese version. Maybe in the footer?

**Comment by k-kuwahara** [comment]
Yes. We also wanted a link to Japanese. If you want to attach it, I think a footer is good.
