### ISSUE TITLE
v4 Documentation

### ISSUE THREAD

**Issue by markgarrigan** [riot/riot.github.io#243]
1. Describe your issue:
The documentation says after setting up an application bundler your code might look like this... index.html has ```<app></app>``` in it. Then in the main.js file it tries to mount the App component to a DOM element with the ID of root.

I think the index.html should have a ```<div id="root"></div>``` instead of ```<app></app>```

2. Can you reproduce the issue?

I can't because I don't know how to make plunkr compile main.js

3. On which browser/OS does the issue appear?

N/A

4. Which version of Riot does it affect?

v4 Documentation

5. How would you tag this issue?

  - [x] Question
  - [ ] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by GianlucaGuarini** [comment]
@markgarrigan thank you for your PR. We can close this issue
