### ISSUE TITLE
Is riot.js v4 unable to compile inline tags/components in the browser?

### ISSUE THREAD

**Issue by exside** [riot/riot.github.io#246]
## Help us to manage our issues by answering the following:

1. Describe your issue:
In v3 [it is possible](https://v3.riotjs.now.sh/guide/compiler/#in-browser-compilation) to specify tags as inline script tags, e.g. 
```html
<!-- inlined tag definition -->
<script type="riot/tag">
  <my-tag>
    <h3>Tag layout</h3>
    <inner-tag />
  </my-tag>
</script>
```
as of v4 the complier does not seem to process such inlined tag-definitions as far as I understand the compiler:

```js
  async function compile() {
    const scripts = $('script[type="riot"]');
    const urls = scripts.map(s => get(s, 'src') || get(s, 'data-src')); // => just looks for URL to fetch!
    // ... rest of code
```

which then leads to runtime errors because `fetch()` is trying to fetch `null` because the inline script tag has no `src` or `data-src` attribute =)...

`Fetch API cannot load file:///path/to/file/null. URL scheme must be "http" or "https" for CORS request.`

is that intentional, e.g. v4 is not supposed to compile inline tag-definitions anymore or did I overlook something?

2. Can you reproduce the issue?

3. On which browser/OS does the issue appear?
all

4. Which version of Riot does it affect?
v4.1.1

5. How would you tag this issue?

  - [x] Question
  - [ ] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by GianlucaGuarini** [comment]
I have transferred this issue since a small doc update is required

**Comment by brauliobo** [comment]
> I have transferred this issue since a small doc update is required

It is still much more complicated than riot 3, having a hard time with riot 4 :(
Before `riot.tag2` accepted a script function, how can you provide the same in riot 4?
