### ISSUE TITLE
Riot.js@4 Japanese translation of indexes (見出しの翻訳について)

### ISSUE THREAD

**Issue by ShiMeiWo** [riot/riot.github.io#249]
トップページや内容のページにある各「見出し」ですが、こちらも翻訳したほうが、初めてドキュメントに触れる人々を威圧しないように感じます。
現状のドキュメントで、リンクと見出し文言がどのように紐付いているのかがまだ詳しく見れていないのですが、もし構造上可能であれば、翻訳をしたほうがいいと思うのですが、いかがでしょうか？

**Comment by k-kuwahara** [comment]
こちら対応し、反映しましたのでクローズ
