### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by tipiirai** [riot/riot.github.io#25]
A cute selector to header to switch between translations.

**Comment by cognitom** [comment]
Definitely. Could you show the version somewhere?

- `en`: latest
- `ch`: v2.2.4
- `ja`: v2.2.4

Maybe in a pulldown or the footer, I think.

**Comment by tipiirai** [comment]
I think pulldown on header and directly listed on footer. Version is important. Good idea. I guess it's best to have them listed on `_config.yml`.

**Comment by cognitom** [comment]
:+1:

**Comment by cognitom** [comment]
@tipiirai ping?
Let me know if there's something I can do. Thanks!

**Comment by tipiirai** [comment]
Sure. Maybe you can just implement it  :) ??

**Comment by cognitom** [comment]
OK, I'll try these:
- add some properties on `_config.yml`
- add a pulldown on header
- add a list on footer

```yaml
# Languages
languages:
  en: latest
  fr: v2.2.4
  ja: v2.2.3
  zh: v2.2.4
```

**Comment by sylvainpolletvillard** [comment]
For the language selector, remember that [flags are not languages](http://flagsarenotlanguages.com/).

**Comment by cognitom** [comment]
Done. @tipiirai could you check #47? Feel free to modify the styles.

@sylvainpolletvillard I c. It's really simple one without any flags ;-)
