### ISSUE TITLE
Link to v3 documentation broken

### ISSUE THREAD

**Issue by skanaar** [riot/riot.github.io#254]
It is a tad hard to find the documentation for Riot v3.

This page: https://riot.js.org/faq/
points to this page: https://riot.js.org/v3
which returns a 404

**Comment by GianlucaGuarini** [comment]
the link to the old documentation is in the footer https://v3.riotjs.now.sh/

**Comment by skanaar** [comment]
I would recommend to not close issues until they are fixed. And the faq link still points to the dead https://riot.js.org/v3.

**Comment by GianlucaGuarini** [comment]
@skanaar thank you for pointing it out!
