### ISSUE TITLE
Expression with logical AND operator fails to compile(In-browser compile with inline templates)

### ISSUE THREAD

**Issue by mt-u** [riot/riot.github.io#260]
## Help us to manage our issues by answering the following:

1. Describe your issue:
The following components can not be compiled when using In-browser compilation with inline templates:

```
    <template id="my-tag">
      <my-tag>
        // '&&' operator causes syntaxerror.
        <p if="{ state.flagA && state.flagB }">Hello world!</p>

        <script>
          export default {
            state: {
              flagA: true,
              flagB: true,
            }
          }
        </script>
      </my-tag>
    </template>
```
Error is: SyntaxError: Unexpected token

2. Can you reproduce the issue?
[Please see this plunker.](https://plnkr.co/edit/1udoQXDW3umND63zNcqz?p=preview)

3. On which browser/OS does the issue appear?
Chrome 75.0.3770.142
Firefox 68.0.1

4. Which version of Riot does it affect?
v4.3.5

5. How would you tag this issue?

  - [ ] Question
  - [x] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by mt-u** [comment]
@GianlucaGuarini Thank you for your response!
I understand that it's very hard to explain every case with limited space.
Thanks to you and all the contributors for providing this wonderful library.

**Comment by GianlucaGuarini** [comment]
I am closing this issue since it appears to be more an edge case than something that needs to be documented. Thank you for your feedback
