### ISSUE TITLE
Browser support needs more detailed information

### ISSUE THREAD

**Issue by bradisbell** [riot/riot.github.io#271]
From the [documentation](https://riot.js.org/faq/#which-browsers-are-supported):

> Which browsers are supported?
> Riot.js 4 supports all the major modern browsers. ...

More detailed information here would be helpful:

 - What key browser features does Riot.js rely on, and for what Riot.js functionality?
 - What browsers have been reported to work, and as of when?
 - What browsers are regularly tested against during the course of development?

**Comment by bradisbell** [comment]
Thanks, that browser support matrix is helpful.  Any way to add it to the documentation?

It still doesn't answer the question though how far back browser support goes.  Is there any way to configure Sauce Labs to test and output for older browsers as well?

**Comment by GianlucaGuarini** [comment]
@bradisbell sure this is our config file https://github.com/riot/riot/blob/master/test/saucelabs-browsers.js

Of course updating it doesn't mean that we couldn't be more explicit in our documentation. I think a better explanation of the technologies used in Riot.js would be really cool. I will update the doc asap
