### ISSUE TITLE
double children doms when run both ssr.fragments and riot.mount ?

### ISSUE THREAD

**Issue by rzfang** [riot/riot.github.io#274]
## Help us to manage our issues by answering the following:

1. Describe your issue:
I ran `ssr.fragments` on node.js and `riot.mount` on browser together. `ssr.fragments` for better SEO and `riot.mount` for real user interactive.
Then I found the children doms will be double ?
I expect that `riot.mount` will overwrite the doms by `ssr.fragments`, but it looks like do the append action, not replace.

2. Can you reproduce the issue?
Need node.js environment, still thinking how to demo it.
Let me explain quickly, I have an `<my-component>`:
after `ssr.fragments('my-component', MyComponent,)` on node.js,
I get `<my-component><h2>foo</h2></my-component>`, and response it to browser.
after `riot.mount('my-component')` on browser,
it becomes `<my-component><h2>foo</h2><h2>foo</h2></my-component>`.

3. On which browser/OS does the issue appear?
Linux Mint 18.3
Firefox 69.0.3

4. Which version of Riot does it affect?
Riont V4

5. How would you tag this issue?

  - [x] Question
  - [ ] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by GianlucaGuarini** [comment]
please let's keep this open. A PR to the documentation is highly appreciated

**Comment by GianlucaGuarini** [comment]
closed with https://github.com/riot/riot.github.io/pull/276
