### ISSUE TITLE
RiotControl in v4 riotjs

### ISSUE THREAD

**Issue by lucabassplayer89** [riot/riot.github.io#275]
Hi, is there the possibily to use RiotControl to listen or trigger event in this version of riotjs?
maybe an example would be useful.
or is it recommended to use a riot observer?

**Comment by k-kuwahara** [comment]
via: https://github.com/riot/riot/issues/2777

**Comment by GianlucaGuarini** [comment]
thank you @k-kuwahara let's close duplicate issues
