### ISSUE TITLE
ru/v2.2.4

### ISSUE THREAD

**Issue by kfreiman** [riot/riot.github.io#29]
Russian translation is started https://github.com/kfreiman/riot.github.io.

Помощь приветствуется!

- [x] Common layouts and includes
- [x] index.md
- [x] forum.md
- [x] faq.md
- [x] download.md
- [x] compare.md
- [x] guide
    - [x] index.md
    - [x] application-design.md
    - [x] compiler.md
- [x] api
    - [x] compiler.md
    - [x] index.md
    - [x] misc.md
    - [x] observerable.md
    - [x] route.md

**Comment by cognitom** [comment]
:+1:

**Comment by tipiirai** [comment]
👍 🇷🇺

**Comment by MartinMuzatko** [comment]
:+1:  Thanks for the todo template :yum:

**Comment by kfreiman** [comment]
All done! http://riotjs.com/ru/
