### ISSUE TITLE
Should we translate quotes?

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#31]
Talking about these twitter quotes:

> I looked at the riot.js example, and it feels so clean, it's scary. [@paulbjensen](https://twitter.com/paulbjensen/status/558378720403419137)
> 
> Just messed around with #RiotJS for an hour. Got it setup with Gulp, Browsesify, and Babel in no time. I like it a lot so far! [@AndrewDelPrete](https://twitter.com/AndrewDelPrete/status/630976295011127296)
> 
> Today I have used #riotjs 2.0 for the first time and I could admit that It will be a long term relationship #js highly recommended. [@gianlucaguarini](https://twitter.com/gianlucaguarini/status/559756081862574080)

Should we translate them, or leave them as they are?

Please document in the CONTRIBUTING.md accordingly.

Thanks!

**Comment by kfreiman** [comment]
I think, we should to translate sufficient for understanding. Even if use quotes in English, we should show translation.

**Comment by sylvainpolletvillard** [comment]
I translated them for FR
