### ISSUE TITLE
Sass Preprocessor Example Uses Deprecated Sass Package

### ISSUE THREAD

**Issue by JaredCHall** [riot/riot.github.io#319]
node-sass was deprecated in late 2020. https://www.npmjs.com/package/node-sass
The maintainers recommend switching to dart sass, which can be installed with npm install sass.

Here is updated code for `compiler.md` that uses dart sass. I also added the 'indented' syntax option so that the sass has no extraneous semicolons to be consistent with the riot minimalist style.

(line 293)
```js
import { registerPreprocessor } from '@riotjs/compiler'
import pug from 'pug'
import sass from 'sass'
import babel from '@babel/core'

registerPreprocessor('template', 'pug', function(code, { options }) {
  const { file } = options
  console.log('Preprocess the template', file)

  return {
    code: pug.render(code),
    // no sourcemap here
    map: null
  }
})

registerPreprocessor('css', 'sass', function(code, { options }) {
  const { file } = options
  console.log('Compile the sass code in', file)

  return {
    code: sass.compileString(code, {syntax: 'indented'}).css,
    map: null
  }
})
```

**Comment by GianlucaGuarini** [comment]
Thank you @JaredCHall. Would you mind opening a PR? Thanks

**Comment by JaredCHall** [comment]
@GianlucaGuarini I'd be happy to, but I get permission denied when I try to push a new branch for the PR. I've never contributed to an open source project before, so I apologize if I don't know what I'm doing. Do I need to be added to a whitelist?

The branch I'm trying to push is based off main.
```
$ git push origin feature/update-sass-preprocessor-example-to-use-current-sass
ERROR: Permission to riot/riot.github.io.git denied to JaredCHall.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

and
```
$ git remote -v
origin  git@github.com:riot/riot.github.io.git (fetch)
origin  git@github.com:riot/riot.github.io.git (push)
```

P.S. I've been having a blast building an app with Riot!!

**Comment by JaredCHall** [comment]
@GianlucaGuarini I figured it out! Did not realize I needed to fork in order to create a PR.

**Comment by GianlucaGuarini** [comment]
thank you!
