### ISSUE TITLE
Suggestion: cute version of Riot logo inspired by cute version of React logo

### ISSUE THREAD

**Issue by nibushibu** [riot/riot.github.io#324]
I saw [the logo for the cute version of React](https://react.dev/?uwu=true), and out of sheer curiosity I decided to create a logo for Riot.js.

As a tribute to the React site, why not implement an Easter egg that displays the cute logo version on the Riot.js website as well, by adding parameters, etc.? 😉

<img src="https://github.com/riot/riot.github.io/assets/399949/13478a94-c24b-493d-9931-404cd24270d8" width="360" style="max-width: 100%">

**Comment by GianlucaGuarini** [comment]
Thank you but I had to close the PR due to inactivity.
