### ISSUE TITLE
Proposing a new intro

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#33]
Based on the current issue here: https://github.com/riot/riot/issues/1238#issuecomment-146061847
I thought about writing a tiny intro for the riot book, which appeared to be liked by @tipiirai a lot.

You can find the raw draft of the intro here: 
https://github.com/riot/riot/issues/1238#issuecomment-144644644

I'd love to invite you to think about this too for a minute or two.
TL;DR is at the bottom.

Lets have a look at the original intro.

```
Why do we need a new UI library?

The frontend space is indeed crowded, but we honestly feel the solution is still “out there”. 
We believe Riot offers the right balance for solving the great puzzle.
While React seems to do it, they have serious weak points that Riot will solve.

So — here’s why we need one:
```
## the new intro is based on these thoughts:

Developers worldwide have problems writing web-apps, so they inadvertently flood stackoverflow or other forums.

As riot already says in the intro: `we honestly feel the solution is still “out there”.`
But how is riot "solving the great puzzle" ? 

Every developer has his own dream of writing code.
Is it being organized perfectly, having great tools to rely on or having an easy and comprehensible API.

When I first started to learn javascript, I got cought up in template rendering and eventhandling very quickly. My first app was a mix of handlebars templates and css-selector-attached events.
 At that time, we used angular at work and I was really upset about not really getting it.
Then after browsing webappers, I found a description that got me intrigued about js frameworks again.

```
Riot is against the current trend of boilerplate and unneeded complexity. We think that a small, powerful API and concise syntax are extremely important things on a client-side library. 
```

That description spoke to me, and it gave me energy to start learning something new. Riot kept it's promise: easy but powerful. Soon after, I wrote games, a video-editor, several interactive menus etc.
## Current proposal

I feel that the current intro of Riot isn't as intriguing as it could be.

**So here is my current proposal:**
### Why is Riot for you?

You don't only want to _get stuff done quickly_, you would love to code without nitpicking about the usual roadblocks: eventhandling, dom selections, template rendering and the list of problems grows with the complexity of your project.

Riot was created to serve you as worry-free and agile way of developing apps with all the freedom you desire.

No more begging for answers for your problems on Stackoverflow.

While Riot offers solutions for important parts of your app, you still get to decide the architecture, behaviors, pre-processor, or other tools.

Even a newcomer to JS can quickly get into the few API methods and write apps today.
### What is Riot not?

Not every tool is for every developer. Ember and Angular are pretty complex and often not comprehensible for beginners, but they aim to offer more features.

While Riot handles the most important and essential problems, the original javascript logic are decisions left to the developer. Although the freedom is something to be handled by the developer, to create complicated apps, a bit of background js knowledge is still needed.
Juggling around with objects, arrays, event data and especially organization
is still up to you.

about this book and it's examples
Riots freedom lets everyone write their software in any way they want.
You can use as much or as less of riots tools.

---

Feedback is very much appreciated.
Thanks!

**Comment by tipiirai** [comment]
Looks good. I guess we need a chapter "What is Riot?" as well, which could borrow from the "Riot is against the current trend of boilerplate and unneeded coplexity..." -section and I also want to highlight the importance of custom tags. See: https://github.com/riot/riot/issues/1238#issuecomment-146099567

**Comment by MartinMuzatko** [comment]
Closed due to inactivity
