### ISSUE TITLE
keep 1.0 demo sources alive

### ISSUE THREAD

**Issue by sylvainpolletvillard** [riot/riot.github.io#38]
The current 1.0 guide refers several times to the riot-admin demonstration, but all the links are dead currently, which makes the 1.0 docs quite unusable: http://riotjs.com/guide/demo/

Could you put these sources somewhere, maybe in another repo ?

**Comment by kfreiman** [comment]
+1 for the removing v1.0 guide form docs

**Comment by sylvainpolletvillard** [comment]
Well I just spent ~4 hours to translate it into French so I was not thinking of removing the guide :smile: 
We can just fix the dead links by hosting the 1.0 demo somewhere. Maybe it is already online, I just don't know where.

**Comment by cognitom** [comment]
@sylvainpolletvillard I'm not sure, but might be this one?
https://github.com/muut/riotjs-admin

@kfreiman I think we don't have to translate v1.0 guide. Actually there's no translation in `zh` and `ja`.

**Comment by cognitom** [comment]
Oh, I found that we can try the demo on *wayback machine", kind of.
https://web.archive.org/web/20140714125443/https://muut.com/riotjs/demo/

**Comment by sylvainpolletvillard** [comment]
You should notify the other translators if you decide that translating v1.0 docs is not necessary. This page is the longest one.

**Comment by cognitom** [comment]
Right. We got to add `CONTRIBUTING.md`.

**Comment by MartinMuzatko** [comment]
as I mentioned in my DE-issue: #21 
> Guide - v1.0.md - looooots of text, I will do this last I assume.

**Comment by cognitom** [comment]
@MartinMuzatko pls skip it. I've add [CONTRIBUTING.md](https://github.com/riot/riot.github.io/blob/master/CONTRIBUTING.md) this morning, at last.

**Comment by cognitom** [comment]
@sylvainpolletvillard I've fixed broken links on the v1.0 doc.
http://riotjs.com/guide/v1.0/

- old - http://riotjs.com/guide/demo/
- new - https://github.com/muut/riotjs-admin

It's not a live demo actually, but it seems enough.
