### ISSUE TITLE
Translation maintainers

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#48]
Hi guys, I'm so happy to see the progress on the translations!
`zh`, `ja` and `fr` have finished, and `ru` seems almost done, and `de` has many pages translated already.

I think we should invite them as a maintainer (collaborator) for each language. (if they say ok)
@GianlucaGuarini @aMarCruz @tipiirai @rsbondi  how do you think?

| language | current ver. | maintainer |
| :-- | :-- | :-- |
| en | latest | who? |
| es | _translating_ | @aMarCruz |
| de | _translating_ | @MartinMuzatko |
| fr | v2.2.4 | @sylvainpolletvillard |
| ja | v2.2.3 | @cognitom |
| ru | _translating_ | @kfreiman |
| zh | v2.2.4 | @Centaur |

**Comment by GianlucaGuarini** [comment]
@cognitom I think it's a good idea I will see if I could give them the write permissions only on the `riot.github.io` repo

**Comment by kfreiman** [comment]
ok

**Comment by cognitom** [comment]
:smile:

**Comment by MartinMuzatko** [comment]
Awesome :) I'm glad to help.

**Comment by GianlucaGuarini** [comment]
I have invited all the contributors!

**Comment by cognitom** [comment]
@GianlucaGuarini thanks a lot!

**Comment by sylvainpolletvillard** [comment]
thank you, challenge accepted ;)

Can you give details about what does that implies ? Do we still work with pull requests ?

**Comment by GianlucaGuarini** [comment]
Now all the collaborators have write permissions only on the riot.github.io repo

**Comment by cognitom** [comment]
@sylvainpolletvillard the workflow would be like this. If it's just typo or something, you don't have to stick to PR, I think. Any feed back is welcome.

### Translating

- Create a new translation branch like `fr/v2.2.4`
- Send PRs **to the translation branch** (or push your commits directory)
- Merge it into `master` when the translation has done
- Push a tag like [v2.2.4-fr](https://github.com/riot/riot.github.io/releases/tag/v2.2.4-fr)

### Hot fix for your language

You can fix `master` as a hot fix **only if** you haven't started the translation branch yet.

- Send PRs **to the master branch** (or push your commits directory)


![artboard 1](https://cloud.githubusercontent.com/assets/16032/9560446/6383fc9c-4e4f-11e5-9b2f-0a4e81121f15.png)

**Comment by Centaur** [comment]
Still got 403 trying to push to master.

**Comment by cognitom** [comment]
@Centaur have you confirm the invitation already?
You might have received the mail, or you could see the invitation here.
https://github.com/riot

**Comment by Centaur** [comment]
Ok. My bad. Checked the wrong email. Just pushed the polishment of zh/v2.2.4 doc. Still get some kind of git user.name display issue but the commits are working fine.

**Comment by cognitom** [comment]
@Centaur nice ;-)
SewerRepo is you? If the issue continues, let us know. We'll ask the support of GitHub.

**Comment by Centaur** [comment]
@cognitom Yes. SewerRepo was one of my git account that has been abandoned, but yesterday I  incorrectly set my local git user.email to the one that linked to it.  This has been fixed locally, SewerRepo account has been deleted on github and will not appear in the future. Sorry for the misoperation.

**Comment by cognitom** [comment]
@Centaur no prob ;-)

**Comment by aMarCruz** [comment]
@cognitom , spanish translation is at 80% in the `origin/es/v2.2.4` branch.
have a good day/night.

**Comment by cognitom** [comment]
@aMarCruz oh greeeat! I'll add `es` to the list above ;-)
Have a good day/night, you too.

**Comment by cognitom** [comment]
OK, now the language selector has been added to our site :smile: 
http://riotjs.com/
Thank you all!

**Comment by tipiirai** [comment]
Looks good. Thank you!

**Comment by sylvainpolletvillard** [comment]
@riot/collaborators I decided to stop maintaining the French translation and leave the Riot organization. The reason is that the most active contributor on this project @GianlucaGuarini has repeatedly shown aggressive and condescending behavior on Twitter towards other members of the open-source community. Sharing core values such as mutual respect is essential to preserve team cohesion. Also, public shaming from a core contributor gives a very bad public image of this whole organization, which is why I no longer want to be associated with it. 

Thank you for inviting me in the first place. I hope you'll find out how to fix this and retrieve a convivial and motivating team spirit as it was one year ago.

**Comment by GianlucaGuarini** [comment]
@sylvainpolletvillard thank you for your great contribution and good luck
