### ISSUE TITLE
Fixing Forum link-images

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#50]
Hi there!

For some time, the forum images next to links were okay, but since a couple months ago ( I think since August 13th ) the Images are now displayed as block:

![pleasefixthis](https://cloud.githubusercontent.com/assets/2950505/10814504/b43e67d8-7e26-11e5-82a2-320e14b2bb14.gif)

(see `#main img` - display block and margin 0 0 1rem )

I wanted to look up when exactly this change has happened, but couldn't find it in the [history of style/_base.scss](https://github.com/riot/riot.github.io/commits/master/style/_base.scss)

This really bugs me everytime I see this. Thanks in advance @tipiirai , you really should visit the forums more often :yum:

**Comment by GianlucaGuarini** [comment]
we don't control the forum markup since it's a muut. I am closing this issue because I guess nobody will ever work on this
