### ISSUE TITLE
Formalities

### ISSUE THREAD

**Issue by MartinMuzatko** [riot/riot.github.io#53]
In German, there is a difference between "you" and "you". Where "du" is the more personal form of adress and "Sie" is the more formal.

Especially in German-like languages, there is this difference of formalities expressed in the form of adress. Usually,  you would use "du", as "Sie" is more related to serious businesses like finances, politics etc.

Which should we use?

Please add in the Contributing.md what style of language you'd prefer after we decided.

Thanks

**Comment by kfreiman** [comment]
In Russian, this approach is borrowed from German. I mainly use the "Sie".

**Comment by sylvainpolletvillard** [comment]
Same difference in French between "tu" and "vous". I used the more formal "vous" everywhere in FR docs.

Also, this form is used when talking to several people, which can be relevant if we consider we are talking to a panel of developpers, or a whole development team.

**Comment by kfreiman** [comment]
I suggest this note at CONTRIBUTING.md: 31dfad9. 
@MartinMuzatko, it's just my opinion, you should use most appropriate form for your language )

**Comment by MartinMuzatko** [comment]
thanks @kfreiman  will also use the formal one.
