### ISSUE TITLE
Jekyll filter round not working properly 

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/riot.github.io#58]
The `round` liquid filter  used in the templates does not work properly:

<img width="379" alt="screen shot" src="https://cloud.githubusercontent.com/assets/879612/11049936/4551172e-8742-11e5-85eb-b1e0b97565f7.png">

This issue appears only on github, on my local version everything works as expected

**Comment by cognitom** [comment]
Depends on the version?
Jekyll and Liquid on GitHub are bit old...
https://pages.github.com/versions/

- jekyll: 2.4.0 (current) --- 3.0.0 (latest)
- liquid: 2.6.2 (current) --- 3.0.6 (latest)

**Comment by sylvainpolletvillard** [comment]
so, in the end, we are using precalculated static values ? Note that the decimal format is different depending on languages, so maybe its not a good idea to use too much plain text config variables in templates

**Comment by kfreiman** [comment]
@sylvainpolletvillard, what solution do you propose?

**Comment by sylvainpolletvillard** [comment]
either fixed the Jekyll filter and add a localization filter for number formatting, or putting the value in plain text in the templates so that we can change the format between langs. I know it's a step backward, but it works.

**Comment by kfreiman** [comment]
+1 to the filter because it allow keep values actual, even if translation is not updated.
```{{ site.compare.react | replace: '.', ',' }}```, for example.

**Comment by cognitom** [comment]
It's ok to drop the number smaller than 1, isn't it?

**Comment by cognitom** [comment]
Or...
```html
<script>
(function(){
  var num = {{ site.react_router.size}} / {{site.riot_route_size_min}}
  var roundedLocaleNum = Number(num.toFixed(1)).toLocaleString()
  document.write(roundedLocaleNum)
})()
</script>x bigger
```

**Comment by kfreiman** [comment]
@cognitom, you are right. i just will remove decimals.
