### ISSUE TITLE
weird bug with Jekyll and section titles

### ISSUE THREAD

**Issue by sylvainpolletvillard** [riot/riot.github.io#62]
I managed to get around this issue for french translation v2.2.4, but it will probably become a problem for others translators too.

Jekyll can not handle special characters in section titles. It causes weird id attributes and the genereated DOM has many issues

````
### Boucler sur des tags personnalisés

Vous pouvez également boucler sur des tags personnalisés. Par exemple:
```

generated:
![image](https://cloud.githubusercontent.com/assets/566536/11119921/1758adca-894d-11e5-859a-42013c3aa953.png)

Do you know a way to fix this ? Maybe I should have posted on jekyll repo but I did not find a solution there

**Comment by sylvainpolletvillard** [comment]
This is weird, it may not be related to special chars. I have a similar problem with this:

```
## Changements

Dans les versions précédentes, les parenthèses échappées étaient conservées...
```

The next paragraph is generated with an  `<h1>` tag, and I can't figure out why. Changing "Changements" into "Changes" solves the problem. Very strange :confused:

**Comment by cognitom** [comment]
@sylvainpolletvillard it looks ok in my environment: Chrome / Safari on Mac (El Capitan)

![image](https://cloud.githubusercontent.com/assets/16032/11122441/a0849b8a-899e-11e5-9b8b-2f494cd3a1ba.png)

I've checked Japanese and French pages. What browser are you using?

**Comment by sylvainpolletvillard** [comment]
Chrome.

It may be a bug with Jekyll on Windows, which is not officially supported.

If on branch fr/v2.3.1 all looks okay to you, I think we can merge with master.

**Comment by cognitom** [comment]
I've got the garbled result as you mentioned. I'm using Jekyll 2.5.3. Hmm.
@sylvainpolletvillard have you tried the version 2.4 used in gh-pages?

**Comment by sylvainpolletvillard** [comment]
Trying this now. I'm using 2.5.3 as well

**Comment by sylvainpolletvillard** [comment]
fr/v2.3.1 docs are ready but there remains this issue.

Could you try on another system than Windows ? I am surprised `fr` is the only locale impacted.

**Comment by cognitom** [comment]
@sylvainpolletvillard my environment I used yesterday was Mac.
Could you check your charset when you saved the files? The file has a line `<meta charset="UTF-8">`, but the strings in the attr seem like `latin-1`...

**Comment by cognitom** [comment]
Hmm, I've checked charset of files by myself. All files are saved in `UTF-8`. No prob.
I'm not sure, but [GitHub version has no problem](http://riotjs.com/fr/guide/) as I mentioned above. I think we can publish and check it later on our public site. Go ahead ;-)

**Comment by sylvainpolletvillard** [comment]
Yep, can't find a problem with charset too. Okay, I will PR then but keep this issue open

**Comment by cognitom** [comment]
Merged. Fortunately, it looks OK on the public site.

**Comment by sylvainpolletvillard** [comment]
I thought it could be related to CLRF windows line separators, but converting all to LF (Unix / OSX) did not help.

**Comment by sylvainpolletvillard** [comment]
Did not reproduce this issue with the latest version of Jekyll on Windows 10. Closing this issue.

**Comment by cognitom** [comment]
Nice!
GitHub also has moved to Jekyll v3.0, last month ;-)
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
