### ISSUE TITLE
Lato as default font

### ISSUE THREAD

**Issue by kfreiman** [riot/riot.github.io#64]
Cyrillic-based languages are not supported at default's Proxima Nova font (#30).
I want to switch russian translation to Lato font. But what do you think about set Lato as default font across all site?

Lato font is most similar to Proxima Nova, it's free, have wide languages support. 
Also, Lato looks original - Riotjs.com will not reduce its uniqueness.

Please, check, your language, and note, are you agree to switch at Lato?

agree / maintainer
- [ ] default @tipiirai
- [ ] es @aMarCruz
- [ ] de @MartinMuzatko 
- [x] fr @sylvainpolletvillard 
- [ ] ja @cognitom
- [x] ru @kfreiman
- [ ] zh @Centaur 

Attention! Use Lato v2 from [latofonts.com](http://www.latofonts.com/lato-free-fonts/) because of Google fonts version is obsolete.

**Comment by kfreiman** [comment]
i'll create branch

**Comment by cognitom** [comment]
I have no preference for Lato or Nova, because both fonts include no Japanese glyphs. But Lato seems reasonable.

**Comment by kfreiman** [comment]
Take a look at lato-font branch, please

**Comment by tipiirai** [comment]
Lato is a good global font for all translated sites.
