### ISSUE TITLE
es/v2.2.4

### ISSUE THREAD

**Issue by aMarCruz** [riot/riot.github.io#65]
Spanish translation for v2.2.4 is 99% done.

**Comment by aMarCruz** [comment]
v2.2.4 have broken links in Guide: "Source code" and "Zip file" for the live demo, bellow the first example.
And the same broken links in Guide/Compiler.

Excluding these links, translation is almost ready.

**Comment by cognitom** [comment]
:+1: great!

**Comment by aMarCruz** [comment]
@cognitom , Spanish v2.2.4 is done and merged.

**Comment by cognitom** [comment]
Wow, we have 6 langs of docs, now!

Could you add the `es` to the end of this file?
https://github.com/riot/riot.github.io/blob/master/_config.yml

**Comment by kfreiman** [comment]
@aMarCruz, super!

**Comment by aMarCruz** [comment]
@cognitom , please review the master branch. I don't know if I overwrite changes.

**Comment by cognitom** [comment]
Looks good :-)
Well, alphabetical order is better, isn't it?

**Comment by aMarCruz** [comment]
Thanks. Yes it is, but which language? :)

**Comment by aMarCruz** [comment]
too complex for generic use

**Comment by cognitom** [comment]
`es` should be the top?

```yaml
# Languages
translations:
  es: v2.2.4
  fr: v2.3.1
  ja: v2.2.3
  ru: v2.3.1
  zh: v2.3.1
```

**Comment by sylvainpolletvillard** [comment]
Ha ha, [alphabetical order depending on the language](https://en.wikipedia.org/wiki/Alphabetical_order) :laughing: 

I think ISO basic Latin Alphabet will suit for all.

**Comment by cognitom** [comment]
:+1: ISO basic Latin Alphabet
Our language has no alphabet, so I have never think about it. Interesting! :smile:

**Comment by aMarCruz** [comment]
@cognitom , I never thought in a language without alphabet :) ...your sorting is correct, these names have only ASCII 7bits :+1:
