### ISSUE TITLE
To maintainers: Pls add tags when translation complete

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#69]
@riot/collaborators thanks for your continuous contribution!
Now we have 6 languages completed ;-) `en` `es` `fr` `ja` `ru` `zh`

If you push your commits via PR I can add a tag (ex. `fr/v2.2.4`) manually after merged. But if you push them directly into `master`, I can't track it, sometimes, so **could you pls add tag** by yourself?

I've added some instruction to CONTRIBUTING.md. Have a look at it. Thanks!

> - Send PR to `master` branch and let someone merge it. (PR is preferred way, but, maintainer can merge it directly if the change is small)
> - Remove working branch: ex. `fr/v2.2.4` or `ja/v2.3.0`
> - Add tag: ex. `v2.2.4-fr` or `v2.3.0-ja`
> 
> https://github.com/riot/riot.github.io/blob/master/CONTRIBUTING.md#when-translation-complete

**Comment by cognitom** [comment]
FYI, users can read older docs on GitHub with such a url:
https://github.com/riot/riot.github.io/tree/v2.2.4-fr/fr

Maybe it would be nice to put the link to older versions somewhere.

**Comment by kfreiman** [comment]
@cognitom thanks. I added new tag in branch ru/2.3.1, but its not work. I should have do it in the master.

**Comment by cognitom** [comment]
@kfreiman I've already added `v2.3.1-fr`, `v2.3.1-ru`. No prob. Thanks!

**Comment by sylvainpolletvillard** [comment]
Thanks for the reminder. We both forgot to add tags, so we are even now :stuck_out_tongue: 
Removed fr/v2.3.1 branch
