### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#7]
### Plunker

- [x] [Todo App](https://github.com/riot/riot/tree/master/demo)
- [ ] [Examples on vuejs](https://github.com/txchen/feplay/tree/gh-pages/riot_vue) - can we use? @feplay
- [ ] Flux?
- [ ] Mixin
- [ ] Observable - Timer?
- [x] Router - [Page switching](http://plnkr.co/edit/xkKigXrmX0SaGCgeQKtO?p=preview)

### Others

- [ ] Webpack setups
- [ ] gulp setups
- [ ] Browserify setups
- [ ] Isomorphic App
- [ ] Router - pushState
- [ ] Hackathon starter - cf. [Angular's one](https://github.com/johnlindquist/ng-hackathon-starter)

[Providing the demo on Plunker](https://github.com/riot/riot/issues/1063#issuecomment-131355378) is a nice idea by @GianlucaGuarini :-)
See also https://github.com/riot/riot/issues/1063

**Comment by gregorypratt** [comment]
Could we do something similar to this Angular 2 seed app? Shows off a few aspects..https://github.com/johnlindquist/ng-hackathon-starter

**Comment by cognitom** [comment]
@gregorypratt nice idea! I'll add it above.

**Comment by cognitom** [comment]
@GianlucaGuarini Some could be hosted on Plunker, and some not. How about having a repo for such examples like `riot/examples`?

**Comment by GianlucaGuarini** [comment]
I would prefer a consistent strategy, either we go with one repo `riot/examples` and then we include it in `riot.github.io` via git submodule, or we just use plunker. I would not mix two strategies.
I like your idea of having `riot/examples` but I don't know how we could test all these examples on any riot release. Unit tests with Travis hooks? Is this even possible?

**Comment by cognitom** [comment]
Agreed, it seems impractical to make full tests by ourselves. But we could fix the Riot version of examples, it seems enough for me (at least as a starting point). I think users would help us, too :smile:
If examples are on GitHub, we could send and receive PR, but I'm not sure how to manage these if on Plunker. Thoughts?

It would be great If plunker has a API for creating a recipe...

**Comment by GianlucaGuarini** [comment]
You can start creating `riot/examples` each folder will be a different example, I will merge it in riot.github.io as git submodule

**Comment by cognitom** [comment]
Sure! Thanks.

Oh! We can send the code to Plunker via POST, maybe!
https://docs.angularjs.org/api/ngRoute/service/$route#example

**Comment by gregorypratt** [comment]
How about a "Playground" page on the site with one decent seed example hosted in an embedded Plunker and then simply a "More examples" link to the riot/examples repo? 

You get best of both worlds then. Also easy to maintain.

**Comment by GianlucaGuarini** [comment]
@cognitom @gregorypratt Wow two cool ideas, ok can we test them in a `riot/examples` repo?

**Comment by cognitom** [comment]
I've created a repository and add some examples.
https://github.com/riot/examples

@GianlucaGuarini can I activate `gh-pages` on the repo? It will make it easy to test them.

@gregorypratt "Playground" sounds nice :+1: 
If you have time, pls fix my broken English in [the documents](https://github.com/riot/examples/blob/master/README.md) of the repo...

**Comment by cognitom** [comment]
I'd like to re-open this issue on the new repo. Thanks!
https://github.com/riot/examples/issues/1

**Comment by GianlucaGuarini** [comment]
@cognitom ok enable the `gh-pages` branch, and maybe make also and index.html in the root where all the links to the examples are listed

**Comment by cognitom** [comment]
@GianlucaGuarini `gh-pages` activated. `index.html` is not yet. I'll make some generator for it.

**Comment by GianlucaGuarini** [comment]
thank you @cognitom you've done a great job!
