### ISSUE TITLE
Jade documentation

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/riot.github.io#77]
According to [this issue](https://github.com/riot/riot/issues/1375) it seems that some users may need help using riot with jade so we may need to consider dropping some lines about it

**Comment by EvanHahn** [comment]
Jade is also now [being renamed to Pug for legal reasons](https://github.com/pugjs/jade/issues/2184), which is another thing to watch for.

**Comment by gawin** [comment]
This is a working example of [issue 1375](https://github.com/riot/riot/issues/1375) for future reference.
Hopefully it might help someone some day.

```
todo
  h3 Todo
  ul
    li(each="{ items }")
      label(class="{ completed:done }")
        input(type="checkbox", checked="{ done }", onclick="{ parent.toggle }")
        = "{ title }"

  form(onsubmit="{add}")
    input(name="input", onkeyup="{edit}")
    button(disabled="{!text}")= "Add { items.length + 1 }"

  script.
    var self = this
    self.items = []
    self.disabled = true

    edit(e) {
      self.text = e.target.value
    }

    add(e) {
      if (this.text) {
        self.items.push({ title: this.text })
        this.text = this.input.value = ''
      }
    }

    toggle(e) {
      var item = e.item
      item.done = !item.done
      return true
    }
```

**Comment by k-kuwahara** [comment]
@GianlucaGuarini 
I think that this issue is solved by rewriting it with the sample code written by @gawin , but what do you think?

**Comment by GianlucaGuarini** [comment]
@k-kuwahara please make a PR to update it

**Comment by GianlucaGuarini** [comment]
doc updated thanks you @k-kuwahara
