### ISSUE TITLE
Dead links on riotjs.com/guide/compiler/

### ISSUE THREAD

**Issue by Aprillion** [riot/riot.github.io#81]
There are dead links in documentation, e.g. on http://riotjs.com/guide/compiler/ the target of live demo links no longer exist, such as:

`<a href="http://muut.github.io/riotjs/demo/">In-browser compiled</a>`

Expected:

* please replace by working links (to the actual demo in this case)
* ideally also automatically check for dead links

(issue manually migrated from https://github.com/riot/riot/issues/1417)

**Comment by GianlucaGuarini** [comment]
The right link is this one http://riotjs.com/examples/todo-app-precompiled/ because we have opensourced all the examples https://github.com/riot/examples

**Comment by Aprillion** [comment]
if I find time to fix this myself, should I update the translated versions too or english only and leave it up to the translators to merge from english into their versions please?

**Comment by GianlucaGuarini** [comment]
Just pull request on the en version and I will be happy to merge it thanks

**Comment by Aprillion** [comment]
any preference for/against relative links such as [In-browser compiled](/examples/todo-app-precompiled/)?

**Comment by Aprillion** [comment]
Testing (manual): the updated links work fine.

Opened https://github.com/riot/examples/issues/17 though.
