### ISSUE TITLE
"Experimental" section in comparison with Polymer out of date

### ISSUE THREAD

**Issue by flash1293** [riot/riot.github.io#84]
The "Experimental"-section in the Polymer-comparison (http://riotjs.com/compare/#experimental) is out of date - the support is much better now (http://jonrimmer.github.io/are-we-componentized-yet/) and microsoft will implement webcomponents eventually (https://blogs.windows.com/msedgedev/2015/07/15/microsoft-edge-and-web-components/)

Especially the last sentence ("It’s uncertain whether Web Components will ever be natively supported.") isn't true anymore.

**Comment by GianlucaGuarini** [comment]
Do you really think there is enough support? http://caniuse.com/#search=web%20components

**Comment by flash1293** [comment]
I didn't talk about the browser-support. Both Edge and Safari work actively at Web Component Support; it's just a matter of time till they are supported.

**Comment by tipiirai** [comment]
You are right. Web component spec has indeed evolved and will continue to do so. 

I stripped out the experimental section and wrote a quick web components vs Riot comparison:

http://riotjs.com/compare/#web-components

**Comment by flash1293** [comment]
:+1:
