### ISSUE TITLE
Japanese documentation

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#9]
I've just started the branch `ja`.
https://github.com/riot/riot.github.io/tree/ja/ja

This branch is WIP yet, but I'd like to finish the translation in a few days. Any feedback and PR to ~~`ja`~~ ~~`master`~~ [ja/v2.2.4 branch](https://github.com/riot/riot.github.io/tree/ja/v2.2.4) is welcome.

- [x] トップ: 
- [x] 比べてみる: 
- [x] FAQ: 
- [x] ガイド
  - [x] カスタムタグ: 
  - [x] コンパイラ: 
  - [x] アプリケーション設計: 
- [x] API
  - [x] カスタムタグ:
  - [x] コンパイラ:
  - [x] オブザーバブル:
  - [x] ルータ: 
  - [x] その他: 
- [x] ダウンロード: 
- [x] フォーラム: 

cc: @narikei @srockstyle @tao-s

**Comment by cognitom** [comment]
Sorry, *only* in this thread, we'd like to discuss in Japanese:

このスレッドは、日本語で進めようかと思います。
@narikei さん、@srockstyle さん、@tao-s さん、声かけていただいてありがとうございました! 宜しくお願いします! あと、GitHubアカウントがわからなかったのですが、[kuwahara_jsar](https://twitter.com/kuwahara_jsar)さんも興味ありとのこと。

- **翻訳**: APIのところ未着手あり。よかったら宣言してから翻訳してみてください。
- **校正**: 翻訳の完了している部分から素読みして、文意の通らないところ、伝わりにくいところがあれば指摘お願いします!

プルリクエストを送る場合は、`ja`ブランチにどぞ。その場合、他の開発者にも話が伝わるように、Issueのタイトルは英語で。翻訳に関するコメントは日本語でも許して(?)もらえるかと思います。

**Comment by cognitom** [comment]
@yasulab 作業の進め方とか、アドバイスあればぜひ ;)

**Comment by cognitom** [comment]
コンパイラについて完了。これで、ガイドはすべて翻訳できました。

**Comment by yasulab** [comment]
@cognitom Sorry to reply :sweat_drops: 
(cc/ @hanachin )

The continuous translation system we're developing works like this:

[<img width="1168" alt="continuous_translation_system" src="https://cloud.githubusercontent.com/assets/155807/9428107/64f24e50-49d9-11e5-868a-93e1e688498e.png">](https://speakerdeck.com/yasulab/how-we-continuously-translate-railsguides)
cf. see [How We Continuously Translate Rails Guides - SpeakerDeck](https://speakerdeck.com/yasulab/how-we-continuously-translate-railsguides) for details.

And our web service being developed can automatically do the followings:

1. monitor origin repo
2. detect commit
3. call Gengo API 
4. create PR

The point is we need money to automate translation using [The Gengo API](http://developers.gengo.com/). So somehow we need to make money to automate. 

In our case of [RailsGuides in Japanese](http://railsguides.jp/), we convert markdown files into ebooks (PDF/Epub) w/ [ReVIEW](https://github.com/kmuto/review), and sell them at [Gumroad](https://gumroad.com/). And it's enough to pay the cost.

_NOTE: Maybe you can also do fundraising, but considering Japanese culture (less donation culture), I think generating ebooks from source files and selling them at Gumroad would be easy and simple. And if you're not familiar with ReVIEW, maybe we can support by sharing our knowledge of implementing convertor._

Hope our experiences useful for this translation project!

**Comment by cognitom** [comment]
Hi, @yasulab. At the starting point, we haven't think about fundraising or using paid services like Gengo. These seems not match our current phase. We'd like to just translate English document into Japanese, simply with ease.
We're using GitHub pages to publish the document, so what we need is just markdown(en) to markdown(ja) conversion. Making epub sounds great, but let us start simple :)

**Comment by cognitom** [comment]
Then, my question would be... what's the best practice:

- to translate the doc continuously and keep catching up the latest version
- to check the diff of source doc and match it to dest language
- to share the translation memory (ex. Google Translation Toolkit)

I'll be very happy if you share the great experience of Rails Tutorial. Thanks.

**Comment by yasulab** [comment]
> We'd like to just translate English document into Japanese, simply with ease.

Oops! Sorry, I just misunderstood that you finished whole translation and wanted to automate :sweat_drops:

**Comment by yasulab** [comment]
I need to leave now, but short answer is in order to do the three, we're developing web services! And it has an option to not use Gengo API :star2:

**Comment by cognitom** [comment]
Oh, great! Let us know the detail when u have a time :+1:

**Comment by yasulab** [comment]
Rgr! :okay_hand:

By the way, we opensourced some of components like [yasslab/konjak](https://github.com/yasslab/konjak). So, of course you can make almost same system as the one we're developing!

But as the konjak repo demonstrates, required system is so complex that we determined to develop a web service to make it simple :)

Anyway, I'll drop by your OSS cafe when you're back!

**Comment by cognitom** [comment]
@yasulab sounds great! Thanks a lot :smile_cat: 

「API / カスタムタグ」完了

**Comment by cognitom** [comment]
@narikei @srockstyle @tao-s 翻訳(というか下訳)、完了しました! :tada: 

#11 で一旦取り込んで良いか、打診中。言語リンクは後でつけるとして、[サイト上](http://riotjs.com/ja/)(公開はまだ)で見られようになるとレビューしやすいかと思います。

- 日本語的に大丈夫か
- 用語は適切か (後述)
- 現バージョンとの不整合がないか (v2.2当時に翻訳した部分もあるので)

このあたりをチェックしていただけると嬉しいです :smile: 

用語についてですが、次の2点が一番気になっています。ご意見ください!

- **expression**: タグのHTML内で使えるJavaScriptのこと。CoffeeScriptのinterpolationに近いです。苦肉の策で「**テンプレート変数**」としましたが、文脈によって微妙なケースもあるようなないような。
- **observable**: 用語としてはカタカナで「**オブザーバブル**」とし、コードや関数名を指している場合は、英語で"observable"としました。違和感ないでしょうか?

**Comment by cognitom** [comment]
We're going to have a small meetup about translating Riot.js on next Wednesday, at Shimokitazawa in Tokyo. If you have a time, come and join us! 

来週の水曜日、翻訳の勉強会をやろうかと思っています。みなさんももしタイミング合えばぜひ!
https://www.facebook.com/events/122851021397256/

**Comment by cognitom** [comment]
I've made a new branch for fixing translation. I'm closing this issue, and open another one for adapting v2.2.4.
https://github.com/riot/riot.github.io/tree/ja/v2.2.4

See also #16, thanks.
