### ISSUE TITLE
ja/v2.3.12

### ISSUE THREAD

**Issue by cognitom** [riot/riot.github.io#93]
I've made a new branch `ja/v2.3.12`. Feel free to send your PR to it :-)
#### Notes
- Pls be aware that we've skipped `ja/v2.2.4` #19, so there could be some inconsistency between versions.
- The PRs on `ja/v2.2.4` is already merged into `ja/v2.3.12`

**Comment by cognitom** [comment]
Here's a check list for v2.2.4. I'll check them later. #92

- [ ] Drop IE8 https://github.com/riot/riot.github.io/commit/1dfa717c576f686c22fc31e4c75096e3d8805ed0
- [ ] Minor changes https://github.com/riot/riot.github.io/commit/4bb13d2a6ac5465b38b44d7efa6e53071aa97c80
- [ ] Home page fixes https://github.com/riot/riot.github.io/commit/7d7b85b3d0765e076961156a854990b2699ca3d9
- [ ] Fix grammar/style and add scoped css to list https://github.com/riot/riot.github.io/commit/9a9af8b20196b5eacf26e3ff9100b840545ed113
- [ ] info regarding the usage of underscore-prefixed variables https://github.com/riot/riot.github.io/commit/8a395d839fe28b3fcbb0c6a067f41ddf964f80ae
- [ ] Correct guide/index.md typo https://github.com/riot/riot.github.io/commit/4c1107f85db99c1f61685b8a779e0d15c9d5dfcd

**Comment by eliot-akira** [comment]
Additional note: while working on the updated translations, I found that Jekyll - more specifically `redcarpet` used for Markdown rendering - had an issue with properly rendering headers with Japanese characters. It's currently an open ticket on redcarpet's repo: #538.

**Comment by eliot-akira** [comment]
`ja/index.md` のヘッダ「A React-like user interface micro-library」を訳すのはどうでしょうか？他の言語ではやってるみたいです。と言っても、切れ味のいい和訳、どうも思いつきません。

**Comment by cognitom** [comment]
同じく思いつかず、そのままにしていました...。
直訳を諦めて「今一番コンパクトな、UIコンポーネントライブラリ」とかでしょうか。
代案あればぜひ! ><

**Comment by cognitom** [comment]
ひとまず、v2.3.12公開しました!
http://riotjs.com/ja/

しばらく`ja/v2.3.12`ブランチは残しておきますので、調整点あればまたPRください。訳語も良いのがでてきたら、差し替えましょう ;-)

**Comment by eliot-akira** [comment]
:smile_cat: :tada:
